config/routes.rb
Rails.application.routes.draw do
  root 'addresses#index', as: 'home'

  get 'about' =>"pages#about"

  resources :addresses
end

app/models/address.rb
class Address < ApplicationRecord
    validates :name, presence: true
    validates :address, presence: true
    validates :email, presence: true
    validates :phone, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
    def index
        @addresses = Address.all.sort_by { |a| a.name.downcase }
    end

    def new
        @title = "New Address";
        @address = Address.new()
    end

    # Crud functon stuff
    #   Create
    def create
        @address = Address.new(address_params)

        if(@address.save)
            redirect_to @address
        else
            render "new"
        end
    end

    #   Read
    def show
        @address = get_address
        @title = @address.name
    end

    #   Update
    def edit
        #just sending stuff to edit page
        @address = get_address
        @title = "Edit " + @address.name
    end

    def update
        @address = get_address

        if(@address.update(address_params))
            redirect_to @address
        else
            render "edit"
        end            
    end

    def destroy
        @address = get_address
        @address.destroy

        redirect_to addresses_path
    end

    # Helper methods
    private def get_address
        return Address.find(params[:id])
    end

    private def address_params
        params.require(:address).permit(:name, :address, :email, :phone)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/edit.html.erb
<h1><%=@title %></h1>
<%= form_for :address, url: address_path(@address), method: :patch do |f| %>
    <% if @address.errors.any? %>
        <% @address.errors.full_messages.each do |err| %>
            <div class="alert"><%=err%></div>
        <% end %>
    <% end %>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
    
    <%= f.label :address %><br>
    <%= f.text_area :address %><br>
    
    <%= f.label :email %><br>
    <%= f.text_field :email %><br>
    
    <%= f.label :phone %><br>
    <%= f.text_field :phone %><br>
    
    <%= f.submit "Edit address" %><br>
<% end %>

app/views/addresses/index.html.erb
<h1>Addresses</h1>
<% if @addresses.length() > 0 %>
    <% @addresses.each do |address| %>
        <div class="address" >
            <h3> <%= address.name%> </h3>
            <p>Address:<br> <%= address.address%> </p>
            <%= link_to "See whole address", address_path(address), :class => 'btn' %>
        </div>
    <% end %>
<% else %>
    <p>It looks like there are no addresses, add one <%= link_to "here", new_address_path, :class => 'btn'%><p>
<% end %>

app/views/addresses/new.html.erb
<h1><%=@title %></h1>
<%= form_for :address, url: addresses_path do |f| %>
    <% if @address.errors.any? %>
        <% @address.errors.full_messages.each do |err| %>
            <div class="alert"><%=err%></div>
        <% end %>
    <% end %>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
    
    <%= f.label :address %><br>
    <%= f.text_area :address %><br>
    
    <%= f.label :email %><br>
    <%= f.text_field :email %><br>
    
    <%= f.label :phone %><br>
    <%= f.text_field :phone %><br>
    
    <%= f.submit "Add new Address" %><br>
<% end %>

app/views/addresses/show.html.erb
<h1><%= @title%></h1>
<p>Address:<br> <%= @address.address%></p>
<p>Email:<br> <%= @address.email%></p>
<p>Phone:<br> <%= @address.phone%></p>
<%=  link_to "Edit", edit_address_path(@address), :class=> "btn" %>
<%=  link_to "Delete", address_path(@address), method: :delete, :class=> "btn" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyAddress <%=
      if(@title) 
        "| "+@title 
      end
    %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <%=  link_to "Home", home_path, :class => 'tabs' %>
      <%=  link_to "Add Address", new_address_path, :class => 'tabs' %>
    </nav>
    <main>
      <%= yield %>
    </main>
  </body>
</html>